# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1b85f7ad6f32ecee34ac13af61dd4c6a3f8e4076b45ec7027dce0e5060b4f3dc6b2f7d92f5ba78675fc269b21576c451714dfb572e078534b48fa90281201e9

test:
  secret_key_base: adc487e0881a21f2fd0cdf5f1bf5647dbafc69f7d3e3da9b28ce76f4d78b5299e0c91fe6acf5c2a4c84ba42deb9b84f82f0e3ddfddb9eff8aa6cf7d278c4403c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
